modLoader = "javafml"
loaderVersion = "[40,)"
license = "Affero GNU General Public License version 3 (AGPLv3)"

[[mods]]
modId = "cursed_land"
version = "0.4.0-beta"
displayName = "Cursed Land"
credits = "Some part of this mod created by MCrator"
displayURL = "https://leanhe.dev"
authors = "KunoiSayami"

[[dependencies.cursed_land]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"
